import router from '@ohos.router'
import userPreferences from '@ohos.data.preferences'
import { CommonConstants } from '../../common/constants/CommonConstants'
import LoginService from '../../service/LoginService'
import UserInfo from '../../viewmodel/user/UserInfo'
import RegionInfo from '../../viewmodel/user/RegionInfo'
import KlassInfo from '../../viewmodel/user/KlassInfo'
import PreferencesUtil from '../../common/util/PreferencesUtil'
import UserService from '../../service/UserService'

@Extend(Column) function content_formant(){
  .padding({top: 30, bottom: 35})
  .borderRadius(CommonConstants.DEFAULT_10)
  .width(CommonConstants.THOUSANDTH_940)
  .backgroundColor(Color.White)
  .height(90)
  .shadow({
    radius: 6,
    color: "#000000",
    offsetX: 0,
    offsetY: 2,
  })
}


@Component
export default struct Tabs_Mine {
  // user: UserInfo = new UserInfo( 0, '用户1', '', '', new RegionInfo(), '', '', new KlassInfo(0, '1', '盘城小学', '一年级'))
  // @State user1: UserInfo = new UserInfo( 0, '用户1', '', '', new RegionInfo(), '', '', new KlassInfo(0, '1', '盘城小学', '一年级'))

  @Link userPersonal: UserInfo/* = new UserInfo( 0, '用户1', '202283290123', '123456', new RegionInfo(1, '南京'), '女', '', new KlassInfo(0, '（1）', '盘城小学', '一年级', '李梅'), '18912345678', '123456789@qq.com')*/
  /*
  async aboutToAppear(){
    console.log('Tag', 'Mine：aboutToAppear')

    this.user1.name = await PreferencesUtil.getPreferenceValue('MyPreferences', 'UserName', '默认名') as string

    console.log('Tag', this.user1.name)
  }
  */


  build() {
    Column(){
      //1 首部
      if (this.userPersonal.id != 0){
        Column(){
          Row(){
            //1 头像
            Row(){
              Image($r('app.media.userhead_example2'))
                .height(77)
                .width(77)
                .backgroundColor($r('app.color.light_gray'))
                .clip(true)
                .borderRadius(77)
            }

            //2 信息
            Column(){
              Row(){
                //姓名
                Text(this.userPersonal.name)
                  .fontSize(20)
              }
              .height(50)
              .width('100%')

              Row(){
                //学校
                if (this.userPersonal.ifBinding) {
                  Text(this.userPersonal.klass.school)
                } else {
                  Text('未认证学校')
                }


                Blank()

                //几年级
                Text(this.userPersonal.klass.grade)

                //班级
                // Text(this.userPersonal.klass.name+'班')

                Blank()
              }
              .height(50)
              .width('100%')
            }
            .justifyContent(FlexAlign.Center)
            .height('100%')
            .width(200)

            //3 进入
            Row(){
              Image($r('app.media.enter'))
                .width(20)
                .height(28)
            }
          }
          .justifyContent(FlexAlign.SpaceBetween)
          .alignItems(VerticalAlign.Center)
          .width('90%')
          .height('100%')
        }
        .width('100%')
        .height(120)
        .backgroundColor($r('app.color.start_window_background'))
        .shadow({
          radius: 6,
          color: "#000000",
          offsetX: 0,
          offsetY: 2,
        })
        .onClick(() => {
          console.log('Tabs',`Mine user.gender = ${this.userPersonal.gender}`)

          router.pushUrl(
            {
              url: 'pages/mine/personal_information/PersonalnformationPage',
              params: {
                data: this.userPersonal,
                ifSuccess: 1
              }
            }
          )
        })

      } else {
        Column(){
          Row(){
            //1 头像
            Row(){
              Image($r('app.media.user'))
                .height(77)
                .width(77)
                .backgroundColor($r('app.color.light_gray'))
                .clip(true)
                .borderRadius(77)
            }

            //2 信息
            Column(){

              Text('欢迎来到墨韵智教')

            }
            .justifyContent(FlexAlign.Center)
            .height('100%')
            .width(160)

            //3 登录/注册
            Row(){
              Button('登录/注册')
                .fontSize(14)
                .fontColor($r('app.color.blue'))
                .backgroundColor($r('app.color.mid_gray'))
            }
          }
          .justifyContent(FlexAlign.SpaceBetween)
          .alignItems(VerticalAlign.Center)
          .width('90%')
          .height('100%')
        }
        .width('100%')
        .height(120)
        .backgroundColor($r('app.color.start_window_background'))
        .shadow({
          radius: 6,
          color: "#000000",
          offsetX: 0,
          offsetY: 2,
        })
        .onClick(() => {
          console.log('Tabs',`Mine user.gender = ${this.userPersonal.gender}`)

          router.replaceUrl(
            {
              url: 'pages/login/LoginPage'
            }
          )
        })
      }


      //2 内容
      Column({space: CommonConstants.SPACE_12}){
        //1 我的收藏
        Column(){
          Row(){
            Row(){
              Image($r('app.media.mine_collect'))
                .width(24)
                .height(24)

              Text($r('app.string.mine_collect'))
            }
            .width(120)
            .justifyContent(FlexAlign.SpaceEvenly)

            Blank()

            Row(){
              Image($r('app.media.enter'))
                .width(20)
                .height(28)
                .margin({"top":"10.00vp","right":"0.00vp","bottom":"0.00vp","left":"0.00vp"})
            }
            .width(40)

          }
          .justifyContent(FlexAlign.SpaceEvenly)
          .alignItems(VerticalAlign.Center)
          .width('100%')
          .height('100%')
        }
        .content_formant()
        .onClick(() => {
          router.pushUrl(
            {
              url: 'pages/mine/mine_collect/MineCollectPage'
            }
          )
        })

        //2 客服中心
        Column(){
          Row(){
            Row(){
              Image($r('app.media.customer_service_center'))
                .width(24)
                .height(24)

              Text($r('app.string.mine_customerServiceCenter'))
            }
            .width(120)
            .justifyContent(FlexAlign.SpaceEvenly)

            Blank()

            Row(){
              Image($r('app.media.enter'))
                .width(20)
                .height(28)
                .margin({"top":"10.00vp","right":"0.00vp","bottom":"0.00vp","left":"0.00vp"})
            }
            .width(40)

          }
          .justifyContent(FlexAlign.SpaceEvenly)
          .alignItems(VerticalAlign.Center)
          .width('100%')
          .height('100%')
        }
        .content_formant()
        .onClick(() => {
          router.pushUrl(
            {
              url: 'pages/mine/service_center/ServiceCenterPage'
            }
          )
        })

        //3 我的设置
        Column(){
          Row(){
            Row(){
              Image($r('app.media.set'))
                .width(24)
                .height(24)

              Text($r('app.string.mine_set'))
            }
            .width(120)
            .justifyContent(FlexAlign.SpaceEvenly)

            Blank()

            Row(){
              Image($r('app.media.enter'))
                .width(20)
                .height(28)
                .margin({"top":"10.00vp","right":"0.00vp","bottom":"0.00vp","left":"0.00vp"})
            }
            .width(40)

          }
          .justifyContent(FlexAlign.SpaceEvenly)
          .alignItems(VerticalAlign.Center)
          .width('100%')
          .height('100%')
        }
        .content_formant()
        .onClick(() => {
          router.pushUrl(
            {
              url: 'pages/mine/mine_set/MineSetPage',
              params: {
                phoneNumber: this.userPersonal.phoneNumber,
                email: this.userPersonal.email
              }
            }
          )
        })

      }
      .margin({top: 20})



    }
    .backgroundColor($r('app.color.light_gray'))
    .width('100%')
    .height('100%')



  }


  //获取个人信息
  getPersonalInformation(){
    let userId = 1

    UserService.getPersonal(userId)
      .then((user) => {
        console.log('Tags', '获取个人信息成功')

        this.userPersonal = user
      })
      .catch((error) => {
        console.log('Tags', '获取个人信息失败')

      })
  }


}